import { FormEvent, useEffect, useMemo, useState } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import './App.css'

type Session = { username: string; csrf_token: string }
type Run = { id: string; ticker: string; analysis_date: string; depth: number | string; status: string; rating: string; created_at: string; elapsed_seconds?: number | string; sections?: Record<string, string> }
type Job = { id: string; status: string; elapsed_seconds: number; error?: string }
const tickers = ['AMD', 'CRWD', 'PANW', 'AVGO', 'MU', 'SPY']
const depths = [
  { value: 1, name: 'Quick', meaning: 'Quick research, few debate and strategy discussion rounds' },
  { value: 3, name: 'Medium', meaning: 'Middle ground, moderate debate rounds and strategy discussion' },
  { value: 5, name: 'Deep', meaning: 'Comprehensive research, in depth debate and strategy discussion' },
]
const labels: Record<string, string> = { market_report: 'Market Analyst', sentiment_report: 'Sentiment Analyst', news_report: 'News Analyst', fundamentals_report: 'Fundamentals Analyst', investment_plan: 'Research Decision', trader_investment_plan: 'Trading Plan', final_trade_decision: 'Portfolio Verdict', complete_report: 'Complete Report' }
async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(path, { ...init, headers: { 'Content-Type': 'application/json', ...(init?.headers || {}) } })
  if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.detail || `Request failed (${response.status})`) }
  if (response.status === 204) return undefined as T
  return response.json()
}
function Login({ onLogin }: { onLogin: (session: Session) => void }) {
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { onLogin(await api('/api/auth/login', { method: 'POST', body: JSON.stringify({ username, password }) })) } catch (err) { setError(err instanceof Error ? err.message : 'Login failed') } finally { setBusy(false) } }
  return <main className="login-shell"><form className="login-card" onSubmit={submit}><div className="eyebrow">PRIVATE ANALYSIS NODE</div><h1>TradingAgents</h1><p>Sign in to the research console.</p><label>Username<input autoComplete="username" value={username} onChange={e => setUsername(e.target.value)} required /></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} required /></label>{error && <div className="error" role="alert">{error}</div>}<button disabled={busy}>{busy ? 'AUTHENTICATING…' : 'SIGN IN'}</button></form></main>
}
export default function App() {
  const [session, setSession] = useState<Session | null | undefined>(undefined); const [runs, setRuns] = useState<Run[]>([]); const [selected, setSelected] = useState<Run | null>(null)
  const [ticker, setTicker] = useState('AMD'); const [analysisDate, setAnalysisDate] = useState(new Date().toISOString().slice(0, 10)); const [depth, setDepth] = useState(3); const [error, setError] = useState(''); const [job, setJob] = useState<Job | null>(null); const [events, setEvents] = useState<string[]>([]); const [raw, setRaw] = useState(false)
  const maxDate = useMemo(() => new Date().toISOString().slice(0, 10), [])
  async function loadHistory() { const history = await api<Run[]>('/api/runs'); setRuns(history); return history }
  useEffect(() => { api<Session>('/api/session').then(value => { setSession(value); return api<Run[]>('/api/runs') }).then(setRuns).catch(() => setSession(null)) }, [])
  async function openRun(run: Run) { setError(''); setRaw(false); try { setSelected(await api<Run>(`/api/runs/${run.id}`)) } catch (err) { setError(String(err)) } }
  async function start(event: FormEvent) { event.preventDefault(); setError(''); setEvents([]); setSelected(null); if (!/^[A-Za-z0-9._\-^=]{1,32}$/.test(ticker.trim())) { setError('Enter a valid ticker symbol.'); return } if (!analysisDate || analysisDate > maxDate) { setError('Choose today or an earlier date.'); return }
    try { const next = await api<Job>('/api/runs', { method: 'POST', headers: { 'X-CSRF-Token': session!.csrf_token }, body: JSON.stringify({ ticker: ticker.trim().toUpperCase(), analysis_date: analysisDate, depth }) }); setJob(next); const stream = new EventSource(`/api/runs/${next.id}/events`); stream.onmessage = async message => { const data = JSON.parse(message.data); setJob(data); if (data.message) setEvents(current => [...current, data.message]); if (data.status === 'done' || data.status === 'failed') { stream.close(); try { await loadHistory(); if (data.status === 'done') setSelected(await api<Run>(`/api/runs/${next.id}`)) } catch { setError('Analysis finished, but the saved report could not be opened.') } } }; stream.onerror = () => { stream.close(); setError('Live update connection closed.') } } catch (err) { setError(err instanceof Error ? err.message : 'Unable to start analysis') } }
  async function logout() { await api('/api/auth/logout', { method: 'POST', headers: { 'X-CSRF-Token': session!.csrf_token } }); setSession(null) }
  if (session === undefined) return <main className="loading">CONNECTING TO ANALYSIS NODE…</main>
  if (!session) return <Login onLogin={value => { setSession(value); loadHistory().catch(() => undefined) }} />
  return <div className="app-shell"><header><div><div className="eyebrow">FINANCE / MULTI-AGENT RESEARCH</div><h1>TradingAgents</h1></div><div className="session"><span className="status-dot"/> {session.username}<button className="ghost" onClick={logout}>Sign out</button></div></header><div className="workspace"><aside>
    <section className="panel"><div className="panel-title"><span>01</span> NEW ANALYSIS</div><form onSubmit={start}><div className="grid-two"><label>Ticker<input aria-label="Ticker" list="ticker-options" value={ticker} onChange={e => setTicker(e.target.value)} maxLength={32}/><datalist id="ticker-options">{tickers.map(item => <option key={item}>{item}</option>)}</datalist></label><label>Analysis date<input type="date" value={analysisDate} max={maxDate} onChange={e => setAnalysisDate(e.target.value)}/></label></div><fieldset><legend>Research depth</legend><div className="depths">{depths.map(item => <label className={depth === item.value ? 'depth active' : 'depth'} key={item.value}><input type="radio" name="depth" checked={depth === item.value} onChange={() => setDepth(item.value)}/><b>{item.value} / {item.name}</b><span>{item.meaning}</span></label>)}</div></fieldset>{error && <div className="error" role="alert">{error}</div>}<button className="run-button" disabled={job?.status === 'queued' || job?.status === 'running'}>{job?.status === 'running' ? 'ANALYSIS RUNNING…' : job?.status === 'queued' ? 'QUEUED…' : 'RUN ANALYSIS'}</button></form></section>
    <section className="panel history"><div className="panel-title"><span>02</span> RUN HISTORY <small>{runs.length}</small></div><div className="history-list" tabIndex={0} aria-label="Analysis run history">{runs.length ? runs.map(run => <button key={run.id} className={selected?.id === run.id ? 'history-row selected' : 'history-row'} onClick={() => openRun(run)} aria-label={`${run.ticker} ${run.analysis_date}`}><span><b>{run.ticker}</b><small>{run.analysis_date} · D{run.depth}</small></span><em className={`rating ${String(run.rating).toLowerCase()}`}>{run.rating || 'Not available'}</em></button>) : <p className="empty">No completed runs.</p>}</div></section></aside>
    <main className="output"><div className="output-bar"><span>03 / ANALYSIS OUTPUT</span>{selected && <button className="ghost" onClick={() => setRaw(!raw)}>{raw ? 'Rendered view' : 'Raw view'}</button>}</div>{job && !selected && <section className="live panel"><div className="live-head"><h2>{job.status.toUpperCase()}</h2><code>{job.elapsed_seconds ?? 0}s</code></div><div className="terminal" aria-live="polite">{events.map((entry, index) => <p key={index}><span>›</span> {entry}</p>)}{job.error && <p className="error">{job.error}</p>}</div></section>}{selected ? <Report run={selected} raw={raw}/> : !job && <section className="welcome"><div className="crosshair">+</div><h2>Awaiting target</h2><p>Configure a ticker, date, and research depth or select a previous run.</p></section>}</main>
  </div></div>
}
function Report({ run, raw }: { run: Run; raw: boolean }) { const sections = Object.entries(run.sections || {}); return <article className="report"><div className="verdict"><div><span>FINAL RATING</span><strong className={`rating ${String(run.rating).toLowerCase()}`}>{run.rating || 'Not available'}</strong></div><dl><div><dt>TICKER</dt><dd>{run.ticker || 'Not available'}</dd></div><div><dt>DATE</dt><dd>{run.analysis_date || 'Not available'}</dd></div><div><dt>DEPTH</dt><dd>{run.depth ?? 'Not available'}</dd></div></dl></div>{sections.length ? sections.map(([key, content]) => <section className="report-section" key={key}><div className="section-head"><h2>{labels[key] || key.replaceAll('_', ' ')}</h2><a href={`/api/runs/${run.id}/download/${key}`}>Download .md</a></div>{raw ? <pre>{content}</pre> : <div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]}>{content}</ReactMarkdown></div>}</section>) : <p className="empty">Report content is not available.</p>}</article> }
